"""add prizes table

Revision ID: 18c6b51fef6f
Revises: 00ac63a08118
Create Date: 2026-09-29 17:11:36.388114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c6b51fef6f'
down_revision: Union[str, Sequence[str], None] = '00ac63a08118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hackathon_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_sets_hackathon_id'), ['hackathon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_sets_id'), ['id'], unique=False)

    op.create_table('prizes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('hackathon_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prizes_id'), ['id'], unique=False)

    op.create_table('calibration_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calibration_set_id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('expected_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_set_id'], ['calibration_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_projects_calibration_set_id'), ['calibration_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_projects_submission_id'), ['submission_id'], unique=False)

    op.create_table('calibration_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calibration_set_id', sa.String(), nullable=False),
    sa.Column('judge_id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_set_id'], ['calibration_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_results_calibration_set_id'), ['calibration_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_results_judge_id'), ['judge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_results_submission_id'), ['submission_id'], unique=False)

    op.create_table('judge_conflicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('judge_id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judge_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judge_conflicts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_conflicts_judge_id'), ['judge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_conflicts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_conflicts_submission_id'), ['submission_id'], unique=False)

    op.create_table('pairwise_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hackathon_id', sa.String(), nullable=False),
    sa.Column('judge_id', sa.String(), nullable=False),
    sa.Column('submission_a_id', sa.String(), nullable=False),
    sa.Column('submission_b_id', sa.String(), nullable=False),
    sa.Column('winner_submission_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'LOCKED', 'CANCELLED', name='pairwisestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_a_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_b_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pairwise_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairwise_evaluations_hackathon_id'), ['hackathon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairwise_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairwise_evaluations_judge_id'), ['judge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairwise_evaluations_submission_a_id'), ['submission_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairwise_evaluations_submission_b_id'), ['submission_b_id'], unique=False)

    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blind_review_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('results_status', sa.String(), nullable=False))

    with op.batch_alter_table('judge_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'RECUSED', 'CANCELLED', name='assignmentstatus'), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assignment_round', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('judge_assignments', schema=None) as batch_op:
        batch_op.drop_column('assignment_round')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.drop_column('results_status')
        batch_op.drop_column('blind_review_enabled')

    with op.batch_alter_table('pairwise_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairwise_evaluations_submission_b_id'))
        batch_op.drop_index(batch_op.f('ix_pairwise_evaluations_submission_a_id'))
        batch_op.drop_index(batch_op.f('ix_pairwise_evaluations_judge_id'))
        batch_op.drop_index(batch_op.f('ix_pairwise_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_pairwise_evaluations_hackathon_id'))

    op.drop_table('pairwise_evaluations')
    with op.batch_alter_table('judge_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judge_conflicts_submission_id'))
        batch_op.drop_index(batch_op.f('ix_judge_conflicts_status'))
        batch_op.drop_index(batch_op.f('ix_judge_conflicts_judge_id'))
        batch_op.drop_index(batch_op.f('ix_judge_conflicts_id'))

    op.drop_table('judge_conflicts')
    with op.batch_alter_table('calibration_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_results_submission_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_results_judge_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_results_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_results_calibration_set_id'))

    op.drop_table('calibration_results')
    with op.batch_alter_table('calibration_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_projects_submission_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_projects_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_projects_calibration_set_id'))

    op.drop_table('calibration_projects')
    with op.batch_alter_table('prizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prizes_id'))

    op.drop_table('prizes')
    with op.batch_alter_table('calibration_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_sets_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_sets_hackathon_id'))

    op.drop_table('calibration_sets')
    # ### end Alembic commands ###
